#(c)2004 sisoft\trg - AYplayer.
# $Id: makefile.win,v 1.16 2004/08/02 09:43:57 root Exp $

#MAKE = wmake

all: help
help:
	echo type 'make real' or 'make adlib' for making.

real:
	$(MAKE) -f src/makefile.win CDEFS=-dLPTPORT=0x378 all
adlib:
	$(MAKE) -f src/makefile.win CDEFS=-dADLIB all

install:
	$(MAKE) -f src/makefile.win install
clean:
	$(MAKE) -f src/makefile.win clean
